#Default properties
#Mon Sep 28 15:26:11 IST 2026
log4j.category.com.cadence.mdv.imc.Main=INFO
log4j.appender.ROLLINGFILE.File=mdv.log
log4j.rootLogger=ERROR, CONSOLE, ROLLINGFILE
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.logger.com.cadence.mdv.bl.impl.core.blNative.BLNative=INFO
log4j.appender.CONSOLE.threshold=FATAL
log4j.appender.ROLLINGFILE.MaxFileSize=100KB
log4j.logger.com.cadence.mdv.services.multitenant.MultiTenantServiceImpl=INFO
log4j.appender.CONSOLE.layout.conversionPattern=%d{HH\:mm\:ss\:SSSS} [%c] [%t] %-5p - %m%n
log4j.appender.ROLLINGFILE.MaxBackupIndex=1
log4j.appender.ROLLINGFILE=org.apache.log4j.RollingFileAppender
log4j.logger.net.ttddyy.dsproxy.listener=DEBUG
log4j.appender.ROLLINGFILE.layout.ConversionPattern=%d{HH\:mm\:ss\:SSSS} [%c] [%t] %-5p - %m%n
log4j.logger.org.hibernate.cfg.annotations.reflection.JPAOverridenAnnotationReader=ERROR
log4j.appender.ROLLINGFILE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
