#Default properties
#Mon Sep 28 15:26:11 IST 2026
security.auth.remoting.enabled=false
security.auth.ldap_port=
security.auth.ldap_user_request=uid
security.auth.ldap_base_dn=
security.auth.ldap_ssl_enabled=false
security.auth.ldap_host=
security.auth.web.enabled=true
security.authorization.enabled=false
